services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: contacts_user
      POSTGRES_PASSWORD: contacts_password
      POSTGRES_DB: contacts_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
    volumes:
      - ./src:/app/src

volumes:
  postgres_data: